// Raw defaults
export const GRID_STEP_HORIZONTAL: number = 5;
export const GRID_STEP_VERTICAL: number = 2;
export const DEFAULT_OBJECT_DISTANCE: number = -20;
export const DEFAULT_PLAYER_DISTANCE: number = -5;

export interface GridProps {
  TOP_LEFT: [number, number, number]
  TOP_CENTER: [number, number, number]
  TOP_RIGHT: [number, number, number]
  BOTTOM_LEFT: [number, number, number]
  BOTTOM_CENTER: [number, number, number]
  BOTTOM_RIGHT: [number, number, number]
}

// Defines possible hostile object positions
export const OBJECT_GRID: GridProps = {
  TOP_LEFT: [-GRID_STEP_HORIZONTAL, GRID_STEP_VERTICAL, DEFAULT_OBJECT_DISTANCE],
  TOP_CENTER: [0, GRID_STEP_VERTICAL, DEFAULT_OBJECT_DISTANCE],
  TOP_RIGHT: [GRID_STEP_HORIZONTAL, GRID_STEP_VERTICAL, DEFAULT_OBJECT_DISTANCE],
  BOTTOM_LEFT: [-GRID_STEP_HORIZONTAL, -GRID_STEP_VERTICAL, DEFAULT_OBJECT_DISTANCE],
  BOTTOM_CENTER: [0, -GRID_STEP_VERTICAL, DEFAULT_OBJECT_DISTANCE],
  BOTTOM_RIGHT: [GRID_STEP_HORIZONTAL, -GRID_STEP_VERTICAL, DEFAULT_OBJECT_DISTANCE],
}

// Defines possible player model positions
export const PLAYER_GRID: GridProps = {
  TOP_LEFT: [-GRID_STEP_HORIZONTAL, 0, DEFAULT_PLAYER_DISTANCE],
  TOP_CENTER: [0, 0, DEFAULT_PLAYER_DISTANCE],
  TOP_RIGHT: [GRID_STEP_HORIZONTAL, 0, DEFAULT_PLAYER_DISTANCE],
  BOTTOM_LEFT: [-GRID_STEP_HORIZONTAL, -0, DEFAULT_PLAYER_DISTANCE],
  BOTTOM_CENTER: [0, -0, DEFAULT_PLAYER_DISTANCE],
  BOTTOM_RIGHT: [GRID_STEP_HORIZONTAL, -0, DEFAULT_PLAYER_DISTANCE],
}